### ISSUE TITLE
求一份源码～

### ISSUE THREAD

**Issue by BigSeer** [Blincheng/Wuzhu#2]

**Comment by Blincheng** [comment]
是有什么需求吗🌚🌚

**Comment by BigSeer** [comment]
你这个助手是基于AccessibilityService实现的吗？想要一份源码，以备日后有别的需求，改改就能用了。嘿嘿。

**Comment by Blincheng** [comment]
是的，基于安卓无障碍服务，这个暂时不开放源码哈，请见谅，写的比较潦草，哈哈哈。

**Comment by BigSeer** [comment]
一起迭代嘛，用了两天都没抢到，服务器时间对的不是很准。

**Comment by Blincheng** [comment]
小米对服务器时间要求不高的，只要提前开始点就可以了，当然已经优化了倒计时
