### ISSUE TITLE
提示: 任务已经开始，但是不在抢购页面

### ISSUE THREAD

**Issue by stickrive** [Blincheng/Wuzhu#5]
![image](https://user-images.githubusercontent.com/22425229/105269827-a8021a00-5bcf-11eb-9f85-0351dc1fd38a.png)
大佬，不是在这个页面抢购么？

**Comment by Blincheng** [comment]
这个应该是没问题的，抢购开始后瞬间点击了，然后按钮变成了[还有机会，看看其他活动]，但是页面还是在这里，脚本还会继续点击，然后跳转到了下一个页面。这时候脚本识别为其他页面了，就停止点击了。可以关注下抢购开始前的Log提示是否正确。或者日志往下翻一下，看看上面的点击是否有成功的情况。
